// Code generated by protoc-gen-go. DO NOT EDIT.
// source: glob_types/types.proto

package glob_types

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MessageType int32

const (
	MessageType_Unknown       MessageType = 0
	MessageType_NewTask       MessageType = 1
	MessageType_MessageNotify MessageType = 2
	MessageType_DeviceNotify  MessageType = 3
)

var MessageType_name = map[int32]string{
	0: "Unknown",
	1: "NewTask",
	2: "MessageNotify",
	3: "DeviceNotify",
}

var MessageType_value = map[string]int32{
	"Unknown":       0,
	"NewTask":       1,
	"MessageNotify": 2,
	"DeviceNotify":  3,
}

func (x MessageType) String() string {
	return proto.EnumName(MessageType_name, int32(x))
}

func (MessageType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_e24fb5be35179f69, []int{0}
}

type DeviceNotifyEvent_NotifyType int32

const (
	DeviceNotifyEvent_Unknown        DeviceNotifyEvent_NotifyType = 0
	DeviceNotifyEvent_DeviceDown     DeviceNotifyEvent_NotifyType = 1
	DeviceNotifyEvent_DeviceUp       DeviceNotifyEvent_NotifyType = 2
	DeviceNotifyEvent_DeviceUnstable DeviceNotifyEvent_NotifyType = 3
)

var DeviceNotifyEvent_NotifyType_name = map[int32]string{
	0: "Unknown",
	1: "DeviceDown",
	2: "DeviceUp",
	3: "DeviceUnstable",
}

var DeviceNotifyEvent_NotifyType_value = map[string]int32{
	"Unknown":        0,
	"DeviceDown":     1,
	"DeviceUp":       2,
	"DeviceUnstable": 3,
}

func (x DeviceNotifyEvent_NotifyType) String() string {
	return proto.EnumName(DeviceNotifyEvent_NotifyType_name, int32(x))
}

func (DeviceNotifyEvent_NotifyType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_e24fb5be35179f69, []int{3, 0}
}

type MessageHeader struct {
	MessageType          MessageType `protobuf:"varint,1,opt,name=message_type,json=messageType,proto3,enum=glob_types.MessageType" json:"message_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *MessageHeader) Reset()         { *m = MessageHeader{} }
func (m *MessageHeader) String() string { return proto.CompactTextString(m) }
func (*MessageHeader) ProtoMessage()    {}
func (*MessageHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_e24fb5be35179f69, []int{0}
}

func (m *MessageHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageHeader.Unmarshal(m, b)
}
func (m *MessageHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageHeader.Marshal(b, m, deterministic)
}
func (m *MessageHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageHeader.Merge(m, src)
}
func (m *MessageHeader) XXX_Size() int {
	return xxx_messageInfo_MessageHeader.Size(m)
}
func (m *MessageHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageHeader.DiscardUnknown(m)
}

var xxx_messageInfo_MessageHeader proto.InternalMessageInfo

func (m *MessageHeader) GetMessageType() MessageType {
	if m != nil {
		return m.MessageType
	}
	return MessageType_Unknown
}

type NewTaskEvent struct {
	MessageType          MessageType `protobuf:"varint,1,opt,name=message_type,json=messageType,proto3,enum=glob_types.MessageType" json:"message_type,omitempty"`
	TaskCount            uint32      `protobuf:"varint,2,opt,name=task_count,json=taskCount,proto3" json:"task_count,omitempty"`
	Customer             uint32      `protobuf:"varint,3,opt,name=customer,proto3" json:"customer,omitempty"`
	Author               uint32      `protobuf:"varint,4,opt,name=author,proto3" json:"author,omitempty"`
	RecipientsCount      uint32      `protobuf:"varint,5,opt,name=recipients_count,json=recipientsCount,proto3" json:"recipients_count,omitempty"`
	Recipients           []uint32    `protobuf:"varint,6,rep,packed,name=recipients,proto3" json:"recipients,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *NewTaskEvent) Reset()         { *m = NewTaskEvent{} }
func (m *NewTaskEvent) String() string { return proto.CompactTextString(m) }
func (*NewTaskEvent) ProtoMessage()    {}
func (*NewTaskEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_e24fb5be35179f69, []int{1}
}

func (m *NewTaskEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewTaskEvent.Unmarshal(m, b)
}
func (m *NewTaskEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewTaskEvent.Marshal(b, m, deterministic)
}
func (m *NewTaskEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewTaskEvent.Merge(m, src)
}
func (m *NewTaskEvent) XXX_Size() int {
	return xxx_messageInfo_NewTaskEvent.Size(m)
}
func (m *NewTaskEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_NewTaskEvent.DiscardUnknown(m)
}

var xxx_messageInfo_NewTaskEvent proto.InternalMessageInfo

func (m *NewTaskEvent) GetMessageType() MessageType {
	if m != nil {
		return m.MessageType
	}
	return MessageType_Unknown
}

func (m *NewTaskEvent) GetTaskCount() uint32 {
	if m != nil {
		return m.TaskCount
	}
	return 0
}

func (m *NewTaskEvent) GetCustomer() uint32 {
	if m != nil {
		return m.Customer
	}
	return 0
}

func (m *NewTaskEvent) GetAuthor() uint32 {
	if m != nil {
		return m.Author
	}
	return 0
}

func (m *NewTaskEvent) GetRecipientsCount() uint32 {
	if m != nil {
		return m.RecipientsCount
	}
	return 0
}

func (m *NewTaskEvent) GetRecipients() []uint32 {
	if m != nil {
		return m.Recipients
	}
	return nil
}

type MessageNotifyEvent struct {
	MessageType          MessageType `protobuf:"varint,1,opt,name=message_type,json=messageType,proto3,enum=glob_types.MessageType" json:"message_type,omitempty"`
	ChatId               uint32      `protobuf:"varint,2,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	AuthorId             uint32      `protobuf:"varint,3,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	ParticipantsLen      uint32      `protobuf:"varint,4,opt,name=participants_len,json=participantsLen,proto3" json:"participants_len,omitempty"`
	Participants         []uint32    `protobuf:"varint,5,rep,packed,name=participants,proto3" json:"participants,omitempty"`
	Length               uint32      `protobuf:"varint,6,opt,name=length,proto3" json:"length,omitempty"`
	Text                 string      `protobuf:"bytes,7,opt,name=text,proto3" json:"text,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *MessageNotifyEvent) Reset()         { *m = MessageNotifyEvent{} }
func (m *MessageNotifyEvent) String() string { return proto.CompactTextString(m) }
func (*MessageNotifyEvent) ProtoMessage()    {}
func (*MessageNotifyEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_e24fb5be35179f69, []int{2}
}

func (m *MessageNotifyEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageNotifyEvent.Unmarshal(m, b)
}
func (m *MessageNotifyEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageNotifyEvent.Marshal(b, m, deterministic)
}
func (m *MessageNotifyEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageNotifyEvent.Merge(m, src)
}
func (m *MessageNotifyEvent) XXX_Size() int {
	return xxx_messageInfo_MessageNotifyEvent.Size(m)
}
func (m *MessageNotifyEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageNotifyEvent.DiscardUnknown(m)
}

var xxx_messageInfo_MessageNotifyEvent proto.InternalMessageInfo

func (m *MessageNotifyEvent) GetMessageType() MessageType {
	if m != nil {
		return m.MessageType
	}
	return MessageType_Unknown
}

func (m *MessageNotifyEvent) GetChatId() uint32 {
	if m != nil {
		return m.ChatId
	}
	return 0
}

func (m *MessageNotifyEvent) GetAuthorId() uint32 {
	if m != nil {
		return m.AuthorId
	}
	return 0
}

func (m *MessageNotifyEvent) GetParticipantsLen() uint32 {
	if m != nil {
		return m.ParticipantsLen
	}
	return 0
}

func (m *MessageNotifyEvent) GetParticipants() []uint32 {
	if m != nil {
		return m.Participants
	}
	return nil
}

func (m *MessageNotifyEvent) GetLength() uint32 {
	if m != nil {
		return m.Length
	}
	return 0
}

func (m *MessageNotifyEvent) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

type DeviceNotifyEvent struct {
	MessageType          MessageType                  `protobuf:"varint,1,opt,name=message_type,json=messageType,proto3,enum=glob_types.MessageType" json:"message_type,omitempty"`
	Device               uint32                       `protobuf:"varint,2,opt,name=device,proto3" json:"device,omitempty"`
	Group                uint32                       `protobuf:"varint,3,opt,name=Group,proto3" json:"Group,omitempty"`
	NotifyType           DeviceNotifyEvent_NotifyType `protobuf:"varint,4,opt,name=notify_type,json=notifyType,proto3,enum=glob_types.DeviceNotifyEvent_NotifyType" json:"notify_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *DeviceNotifyEvent) Reset()         { *m = DeviceNotifyEvent{} }
func (m *DeviceNotifyEvent) String() string { return proto.CompactTextString(m) }
func (*DeviceNotifyEvent) ProtoMessage()    {}
func (*DeviceNotifyEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_e24fb5be35179f69, []int{3}
}

func (m *DeviceNotifyEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeviceNotifyEvent.Unmarshal(m, b)
}
func (m *DeviceNotifyEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeviceNotifyEvent.Marshal(b, m, deterministic)
}
func (m *DeviceNotifyEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeviceNotifyEvent.Merge(m, src)
}
func (m *DeviceNotifyEvent) XXX_Size() int {
	return xxx_messageInfo_DeviceNotifyEvent.Size(m)
}
func (m *DeviceNotifyEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_DeviceNotifyEvent.DiscardUnknown(m)
}

var xxx_messageInfo_DeviceNotifyEvent proto.InternalMessageInfo

func (m *DeviceNotifyEvent) GetMessageType() MessageType {
	if m != nil {
		return m.MessageType
	}
	return MessageType_Unknown
}

func (m *DeviceNotifyEvent) GetDevice() uint32 {
	if m != nil {
		return m.Device
	}
	return 0
}

func (m *DeviceNotifyEvent) GetGroup() uint32 {
	if m != nil {
		return m.Group
	}
	return 0
}

func (m *DeviceNotifyEvent) GetNotifyType() DeviceNotifyEvent_NotifyType {
	if m != nil {
		return m.NotifyType
	}
	return DeviceNotifyEvent_Unknown
}

func init() {
	proto.RegisterEnum("glob_types.MessageType", MessageType_name, MessageType_value)
	proto.RegisterEnum("glob_types.DeviceNotifyEvent_NotifyType", DeviceNotifyEvent_NotifyType_name, DeviceNotifyEvent_NotifyType_value)
	proto.RegisterType((*MessageHeader)(nil), "glob_types.MessageHeader")
	proto.RegisterType((*NewTaskEvent)(nil), "glob_types.NewTaskEvent")
	proto.RegisterType((*MessageNotifyEvent)(nil), "glob_types.MessageNotifyEvent")
	proto.RegisterType((*DeviceNotifyEvent)(nil), "glob_types.DeviceNotifyEvent")
}

func init() { proto.RegisterFile("glob_types/types.proto", fileDescriptor_e24fb5be35179f69) }

var fileDescriptor_e24fb5be35179f69 = []byte{
	// 450 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x53, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0xc5, 0x4e, 0xe2, 0x34, 0x63, 0x27, 0xdd, 0x8e, 0x50, 0x6a, 0x81, 0x90, 0x22, 0x1f, 0x90,
	0xe1, 0x10, 0x24, 0xb8, 0x71, 0x84, 0x22, 0x88, 0x5a, 0x7a, 0x88, 0xda, 0x73, 0xb4, 0xb1, 0x87,
	0xc4, 0x4a, 0xb2, 0x6b, 0xd9, 0x9b, 0x96, 0xfc, 0x00, 0x7e, 0x02, 0xff, 0x92, 0x1f, 0x81, 0xf6,
	0x83, 0xd8, 0x15, 0xc7, 0xf6, 0x62, 0xcd, 0x7b, 0xe3, 0x7d, 0x6f, 0xde, 0x48, 0x03, 0xe3, 0xd5,
	0x56, 0x2e, 0x17, 0xea, 0x50, 0x52, 0xfd, 0xce, 0x7c, 0xa7, 0x65, 0x25, 0x95, 0x44, 0x68, 0xf8,
	0xe4, 0x12, 0x86, 0xdf, 0xa9, 0xae, 0xf9, 0x8a, 0xbe, 0x11, 0xcf, 0xa9, 0xc2, 0x8f, 0x10, 0xed,
	0x2c, 0x61, 0xfe, 0x88, 0xbd, 0x89, 0x97, 0x8e, 0xde, 0x9f, 0x4f, 0x9b, 0x37, 0x53, 0xf7, 0xe0,
	0xe6, 0x50, 0xd2, 0x3c, 0xdc, 0x35, 0x20, 0xf9, 0xe3, 0x41, 0x74, 0x4d, 0xf7, 0x37, 0xbc, 0xde,
	0x7c, 0xb9, 0x23, 0xa1, 0x1e, 0x23, 0x86, 0xaf, 0x00, 0x14, 0xaf, 0x37, 0x8b, 0x4c, 0xee, 0x85,
	0x8a, 0xfd, 0x89, 0x97, 0x0e, 0xe7, 0x03, 0xcd, 0x7c, 0xd6, 0x04, 0xbe, 0x80, 0x93, 0x6c, 0x5f,
	0x2b, 0xb9, 0xa3, 0x2a, 0xee, 0x98, 0xe6, 0x11, 0xe3, 0x18, 0x02, 0xbe, 0x57, 0x6b, 0x59, 0xc5,
	0x5d, 0xd3, 0x71, 0x08, 0xdf, 0x00, 0xab, 0x28, 0x2b, 0xca, 0x82, 0x84, 0xaa, 0x9d, 0x70, 0xcf,
	0xfc, 0x71, 0xda, 0xf0, 0x56, 0x3e, 0x01, 0x68, 0xa8, 0x38, 0x98, 0x74, 0xd2, 0xe1, 0x27, 0x9f,
	0x79, 0xf3, 0x16, 0x9b, 0xfc, 0xf2, 0x01, 0xdd, 0xf8, 0xd7, 0x52, 0x15, 0x3f, 0x0e, 0x8f, 0x0f,
	0x7d, 0x0e, 0xfd, 0x6c, 0xcd, 0xd5, 0xa2, 0xc8, 0x5d, 0xe2, 0x40, 0xc3, 0x59, 0x8e, 0x2f, 0x61,
	0x60, 0x43, 0xe8, 0x96, 0xcb, 0x6b, 0x89, 0x59, 0xae, 0x73, 0x95, 0xbc, 0x52, 0x45, 0x56, 0x94,
	0x5c, 0x27, 0xdb, 0x92, 0x70, 0xc9, 0x4f, 0xdb, 0xfc, 0x15, 0x09, 0x7c, 0x0d, 0x51, 0x9b, 0x8a,
	0x7b, 0xc7, 0x64, 0x0f, 0x78, 0xbd, 0xc2, 0x2d, 0x89, 0x95, 0x5a, 0xc7, 0x81, 0x9d, 0xc3, 0x22,
	0x44, 0xe8, 0x2a, 0xfa, 0xa9, 0xe2, 0xfe, 0xc4, 0x4b, 0x07, 0x73, 0x53, 0x27, 0xbf, 0x7d, 0x38,
	0xbb, 0xa0, 0xbb, 0x22, 0x7b, 0xb2, 0x35, 0x8c, 0x21, 0xc8, 0x8d, 0xe0, 0xbf, 0x2d, 0x58, 0x84,
	0xcf, 0xa1, 0xf7, 0xb5, 0x92, 0xfb, 0xd2, 0x6d, 0xc0, 0x02, 0x9c, 0x41, 0x28, 0x8c, 0xb1, 0x35,
	0xea, 0x1a, 0xa3, 0xb4, 0x6d, 0xf4, 0xdf, 0x74, 0x53, 0x5b, 0x1b, 0x67, 0x10, 0xc7, 0x3a, 0xb9,
	0x04, 0x68, 0x3a, 0x18, 0x42, 0xff, 0x56, 0x6c, 0x84, 0xbc, 0x17, 0xec, 0x19, 0x8e, 0x00, 0xac,
	0xcc, 0x85, 0xc6, 0x1e, 0x46, 0x70, 0x62, 0xf1, 0x6d, 0xc9, 0x7c, 0x44, 0x18, 0x39, 0x24, 0x6a,
	0xc5, 0x97, 0x5b, 0x62, 0x9d, 0xb7, 0x57, 0x10, 0xb6, 0x12, 0x3e, 0x54, 0x0b, 0xa1, 0xef, 0x2e,
	0x85, 0x79, 0x78, 0x76, 0x3c, 0x42, 0x6b, 0xce, 0x7c, 0x64, 0x10, 0xb5, 0x87, 0x66, 0x9d, 0x65,
	0x60, 0x8e, 0xf7, 0xc3, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x61, 0x4b, 0xf6, 0x72, 0xd6, 0x03,
	0x00, 0x00,
}
